### ISSUE TITLE
Web admin doesn't work anymore since the generated static distribution of the UI is no longer a part of the repo (they are now ignored by git)

### ISSUE THREAD

**Issue by dovadi** [akira/exq_ui#30]
Exq_ui doesn't contain the assets anymore since 7a02ab534da99, so the web admin has no longer the needed static assets (js and css) to render properly.

Also building the JS distribution manually myself fails, since ember-validations is no longer found on the given url "http://builds.dockyard.com.s3.amazonaws.com/ember-validations/ember-validations-latest.js"

**Comment by akira** [comment]
@dovadi sorry about that, I published another version to hex with assets that has the assets.

**Comment by dovadi** [comment]
No worries, I understand ...

However looking at the commits, I still don't see the assets added in current master branch https://github.com/akira/exq_ui/tree/master/priv/ember/dist (although you bumped to 0.8.1). Am I missing something?

**Comment by akira** [comment]
@dovadi mix version 0.8.1 has the assets in the hex package. While I took out the generated assets from version control, I still upload them into hex.
